name: 'Setup Codesign'
description: 'Setup codesigning heychains and certificate on a macOS machine'

inputs:
  apple-application-cert:
    description: 'path to the application certificate'
    required: true
  apple-installer-cert:
    description: 'path to the installer certificate'
    required: true
  apple-dev-password:
    description: 'GRIS apple developper password'
    required: true
runs:
  using: "composite"
  steps:
    - name: setup-codesign
      env:

        CODESIGN_APP_SECUREFILEPATH: ${{ inputs.apple-application-cert }}
        CODESIGN_INSTALLER_SECUREFILEPATH: ${{ inputs.apple-installer-cert }}
        APPLE_DEVELOPER_ID_PASSWORD: ${{ inputs.apple-dev-password }}
      shell: bash
      run: |
        echo "1"
        set -x
        echo "3"
        KEY_CHAIN=build.keychain
        security create-keychain -p github2 "$KEY_CHAIN"2
        security default-keychain -s "$KEY_CHAIN"
        security unlock-keychain -p github2 "$KEY_CHAIN"
        echo "4"
        echo "$CODESIGN_APP_SECUREFILEPATH"
        cat gris-app-cert.p12
        if [[ -f "$CODESIGN_APP_SECUREFILEPATH" ]]; then
          echo "4.33"
          security -v import "$CODESIGN_APP_SECUREFILEPATH" -A -k "$KEY_CHAIN" -P "$APPLE_DEVELOPER_ID_PASSWORD" -T /usr/bin/codesign -T /usr/bin/security -T /usr/bin/pkgbuild
          echo "4.66"
        fi
        echo "5"
        if [[ -f "$CODESIGN_INSTALLER_SECUREFILEPATH" ]]; then
          security import "$CODESIGN_INSTALLER_SECUREFILEPATH" -A -k "$KEY_CHAIN" -P "$APPLE_DEVELOPER_ID_PASSWORD" -T /usr/bin/codesign -T /usr/bin/security -T /usr/bin/pkgbuild
        fi
        echo "6"
        security set-key-partition-list -S apple-tool:,apple: -s -k github2 "$KEY_CHAIN"2
        rm -f "$CODESIGN_APP_SECUREFILEPATH" "$CODESIGN_INSTALLER_SECUREFILEPATH"
