name: 'Setup Codesign'
description: 'Setup codesigning heychains and certificate on a macOS machine'

inputs:
  apple-dev-id-application:
    description: 'certificate id for the application'
    required: true
  apple-dev-id-installer:
    description: 'certificate id for the installer'
    required: true
  apple-dev-password:
    description: 'GRIS apple developper password'
    required: true
runs:
  using: "composite"
  steps:
    - name: setup-codesign
      env:

        APPLE_DEVELOPER_ID_APPLICATION: ${{ inputs.apple-dev-id-application }}
        APPLE_DEVELOPER_ID_INSTALLER: ${{ inputs.apple-dev-id-installer }}
        APPLE_DEVELOPER_ID_PASSWORD: ${{ inputs.apple-dev-password }}
      shell: bash
      run: |
        set +x
        if [[ -n "$APPLE_DEVELOPER_ID_APPLICATION" ]]; then
        echo $"APPLE_DEVELOPER_ID_APPLICATION" | base64 --decode > gris-app-cert.p12
        export CODESIGN_APP_SECUREFILEPATH=$PWD/gris-app-cert.p12
        fi
        if [[ -n "$APPLE_DEVELOPER_ID_INSTALLER" ]]; then
        echo "$APPLE_DEVELOPER_ID_INSTALLER" | base64 --decode > gris-installer-cert.p12
        export CODESIGN_INSTALLER_SECUREFILEPATH=$PWD/gris-installer-cert.p12
        fi
        KEY_CHAIN=build.keychain
        security create-keychain -p github "$KEY_CHAIN"
        security default-keychain -s "$KEY_CHAIN"
        security unlock-keychain -p github "$KEY_CHAIN"
        if [[ -f "$CODESIGN_APP_SECUREFILEPATH" ]]; then
        security import "$CODESIGN_APP_SECUREFILEPATH" -A -k "$KEY_CHAIN" -P APPLE_DEVELOPER_ID_PASSWORD" -T /usr/bin/codesign -T /usr/bin/security -T /usr/bin/pkgbuild  > /dev/null 2>&1
        fi
        if [[ -f "$CODESIGN_INSTALLER_SECUREFILEPATH" ]]; then
        security import "$CODESIGN_INSTALLER_SECUREFILEPATH" -A -k "$KEY_CHAIN" -P APPLE_DEVELOPER_ID_PASSWORD" -T /usr/bin/codesign -T /usr/bin/security -T /usr/bin/pkgbuild  > /dev/null 2>&1
        fi
        security set-key-partition-list -S apple-tool:,apple: -s -k github "$KEY_CHAIN"
        rm -f "$CODESIGN_APP_SECUREFILEPATH" "$CODESIGN_INSTALLER_SECUREFILEPATH"
        set -x
